### ISSUE TITLE
403 error posting a checkout request

### ISSUE THREAD

**Issue by rleo79** [sumup/sumup-ecom-php-sdk#19]
I really cannot figure out how to create a checkout request
`
try {
     $sumup = new \SumUp\SumUp([
        'app_id'                   =>  $app_config['app_id'],
        'app_secret'               =>  $app_config['app_secret'],
        'grant_type'               =>  'client_credentials',
        'scopes'                   =>  ['payments', 'transactions.history', 'user.app-settings', 'user.profile_readonly'],
        'use_guzzlehttp_over_curl' =>  $app_config['force_guzzle'],
    ]);
    
    $accessToken = $sumup->getAccessToken();
    $value = $accessToken->getValue();
    
    $checkoutsService = $sumup->getCheckoutService();
    
    $response = $checkoutsService->create(10, 'EUR', 'CO746453', 'docuser@sumup.com', 'Sample one-time payment');
    
    $checkoutId = $response->getBody()->id;
    stampa_info('CHECKOUT ID: '.$checkoutId);
    
} catch (\SumUp\Exceptions\SumUpValidationException $e) {
    die(stampa_errore('Validation error: ' . $e->getMessage() . ' - Code: '.$e->getCode())); 
} catch (\SumUp\Exceptions\SumUpArgumentException $e) {
    die(stampa_errore('Argument error: ' . $e->getMessage() . ' - Code: '.$e->getCode()));
}  catch (\SumUp\Exceptions\SumUpAuthenticationException $e) {
    die(stampa_errore('Authentication error: ' . $e->getMessage() . ' - Code: '.$e->getCode()));
} catch (\SumUp\Exceptions\SumUpResponseException $e) {
    die(stampa_errore('Response error: ' . $e->getMessage() . ' - Code: '.$e->getCode()));
} catch(\SumUp\Exceptions\SumUpSDKException $e) {
    die(stampa_errore('SumUp SDK error message: ' . $e->getMessage() . ' - Code: '.$e->getCode()));
} catch(\SumUp\Exceptions\SumUpServerException $e) {
    die(stampa_errore('SumUp server error message: ' . $e->getMessage() . ' - Code: '.$e->getCode()));
} catch (Exception $e){
    die(stampa_errore('Si è verificato un problema: ' . $e->getMessage() . ' - Code: '.$e->getCode()));
}
`

I get a "Response error: request_not_allowed - Code: 403" exception.
I am sure that $accessToken has a value. So I cannot figure why it's not working.

**Comment by lyubomir-sumup** [comment]
Hi @rleo79,
There is nothing wrong with your code. You are missing the `payments` scope. You can read more about the restricted scopes [here](https://developer.sumup.com/docs/authorization#restricted-scopes). You should write to integration@sumup.com to be properly onboarded for this functionality.

**Comment by chrisreiter** [comment]
what does  " You should write to integration@sumup.com to be properly onboarded for this functionality."   mean?   Is there anything to be activated in the account as well?    I am having that issue on test- and real accounts

**Comment by shahsagar1998** [comment]
Hello everyone,

I got the same issue, and i have added payments scope in my code.
Please check and give me suggestion, how to fix this issue.

$sumup = new \SumUp\SumUp([
  'app_id' => 'SUM_UP_APP_ID',
  'app_secret' => 'SUM_UP_APP_SECRET',
  'grant_type' => 'client_credentials',
  'scopes' => ['payments', 'transactions.history', 'user.app-settings', 'user.profile_readonly'],
]);
$checkoutService = $sumup->getCheckoutService();
$checkoutResponse = $checkoutService->create($amount, $currency, $checkoutRef, $payToEmail);
$checkoutId = $checkoutResponse->getBody()->id;



Thanks in Advance.

**Comment by pratikdzignuts** [comment]
you fill sumup contact form and enabling payment scope. then checkout API
works.
