### ISSUE TITLE
All for creating and modifying bank accounts in the merchant service

### ISSUE THREAD

**Issue by terrypearson** [sumup/sumup-ecom-php-sdk#2]
One key feature of a merchant that is currently missing is the ability to /me/merchant-profile/bank-accounts to add/edit/delete bank accounts. It would be nice to have this.

Thanks!

**Comment by terrypearson** [comment]
Oh that would be great! Thanks for the response. 

Do you know approximately when that would be? (Weeks, Months, Etc). Thank you so much, we are looking at moving to SumUp instead of Stripe and this would help a lot. 

-Terry

**Comment by lyubomir-sumup** [comment]
Hopefully by the end of the month we will have a stable release and it'll include that functionality. I'll notify you in this thread when it's live.

Thank you for using SumUp

**Comment by lyubomir-sumup** [comment]
@terrypearson we now have a stable release, so you can use the [Custom service](https://github.com/sumup/sumup-ecom-php-sdk/blob/master/docs/reference/Custom.md) for the endpoints that are not part of the core functionality of the SDK.

Here is a simple example:
```
$customService = $sumup->getCustomService();
$response = $customService->request('GET', '/v0.1/me/merchant-profile/bank-accounts');
```

**Comment by terrypearson** [comment]
Wonderful... Thank you!
