### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by maisoui** [sumup/sumup-ecom-php-sdk#21]
Hi,

It would be nice to add support to PHP 8 :)

Best regards

**Comment by maisoui** [comment]
Anybody's here? Library still maintained?

**Comment by ptrovatelli** [comment]
security support only of php 7 is coming soon, and end of security support is expected in 16 months.
I'd say it's time to look into this yeap :)

https://www.php.net/supported-versions.php

**Comment by ptrovatelli** [comment]
actually someone made a PR about it. If it's that simple we're good to go :)
https://github.com/sumup/sumup-ecom-php-sdk/pull/26

**Comment by lucasmichot** [comment]
Any news ?

**Comment by CNSam** [comment]
Still no update on this?

**Comment by lucasmichot** [comment]
This issue is open for more than 1 year
I am not sure what is Sumup approach on this - do they want to stop supporting PHP clients ?
If so, that you be a bad strategy

I have already alerted a PM and a VP working at Sumup about this topic, but without any effect

cc. @schabby

**Comment by lucasmichot** [comment]
@AndreeWille @CooperRS @ForsakenHarmony @Lucien @PaulLafytskyi @adriankeenan @afonsodelgado @carlosedj @cecisousa @connor-baer @cristianoliveira @curly-monkey @es1o @felixheck @floschliep @heitor-nsouza @hilleer @hlmerscher @ismaellg @julienschmidt @justman00 @madeinussr @mmiranda @mostafafotoh @nicosommi @olivermaric @robbdimitrov @robinbraemer @rops42 @s0ph1e @sahlone @shagedorn @syndbg @tomarrell @voronianski

**Comment by joelrose** [comment]
Hi, I'm very sorry for the long wait! We have fixed this with the latest release (1.1.0)
