### ISSUE TITLE
SumUpResponseException Client error

### ISSUE THREAD

**Issue by Alkashi** [sumup/sumup-ecom-php-sdk#22]
Hello,

I had this error when trying to connect with this code
$sumup = new \SumUp\SumUp([
      'app_id'     => $client_id,
      'app_secret' => $client_secret,
      'grant_type' => 'password',
      'scopes'      => ['payments', 'transactions.history', 'user.app-settings', 'user.profile_readonly'],
      'username'   => $sumupEmail,
      'password'   => $sumupPwd
    ]);

Everything was working fine for months and tonight I got an SumUpResponseException and this message on the response : 
```
"Client error" 
=> Too many requests, please try again later.))[2] => Array([file] => /homepages/
```

I noticed that the sumup server regulary have pb on we.
Could you please tell me how or when this issue will be solved ?

Many thanks in advance.

**Comment by joelrose** [comment]
Hi, It looks like your account has been rate limited because of too many requests in a short period. If you are still experiencing the same problem, please open a new issue!
