### ISSUE TITLE
error compsoser

### ISSUE THREAD

**Issue by JulioFlausino** [sumup/sumup-ecom-php-sdk#25]
Hi,
Iḿ trying get SKD summup to php excute this command:
composer require sumup/sumup-ecom-php-sdk
and return is
Package sumup/sumup-ecom-php-sdk has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

php version 8.0.5 and composer version2.0

**Comment by maisoui** [comment]
This package isn't compatible with PHP 8.0. I opened an issue to request it, but still no answer.
I hope this package is not dead.
Regards

**Comment by ptrovatelli** [comment]
@JulioFlausino  is this working for you? https://github.com/sumup/sumup-ecom-php-sdk/pull/26

**Comment by joelrose** [comment]
Hi, I'm very sorry for the long wait! We have fixed this with the latest release (1.1.0)
