### ISSUE TITLE
Class not found : ApplicationConfiguration

### ISSUE THREAD

**Issue by prasadsupare** [sumup/sumup-ecom-php-sdk#8]
I've created an index file from where i'am using SumUp class of SumUp.php file from sumup folder, And i'am getting the following error from SumUp.php file:

**Fatal error: Uncaught Error: Class 'SumUp\Application\ApplicationConfiguration' not found in /mnt/stor1-wc1-dfw1/388632/www.xyz.com/web/content/wilson/sumup/sumup/SumUp.php:54 Stack trace: #0 /mnt/stor1-wc1-dfw1/388632/www.xyz.com/web/content/wilson/sumup/index.php(23): SumUp\SumUp->__construct(Array) #1 {main} thrown in /mnt/stor1-wc1-dfw1/388632/www.xyz.com/web/content/wilson/sumup/sumup/SumUp.php on line 54**

**Comment by lyubomir-sumup** [comment]
The recommended way for using the SDK is through [composer](https://getcomposer.org/). Do you use it that way?
Can you provide some example code so we could help you?

**Comment by prasadsupare** [comment]
this is my index file where i've also entered fake details for testing:

`ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);


$card_number='4556305490929885';  
$card_name='Barbara Speaks';
$expiry_month='03';
$expiry_year='2023';
$cvv='053';

$amount=10;
$currency='GBP';
$checkoutRef='CO746453';
$payToEmail='prasadsupare47@gmail.com';

require_once 'sumup/SumUp.php';


try {
			    $sumup = new \SumUp\SumUp ([
			    'app_id'     => 'XN7kd2r0v4Rrilq6PKLZ4xKlLH0u',
			    'app_secret' => '3880a28b7317107cd9f2944c271798680f891d46f2c6782422878120da543316',
			    'grant_type' => 'client_credentials'
			]);
			$accessToken = $sumup->getAccessToken();
			$value = $accessToken->getValue();

    $checkoutService = $sumup->getCheckoutService();
    $checkoutResponse = $checkoutService->create($amount, $currency, $checkoutRef, $payToEmail);
    $checkoutId = $checkoutResponse->getBody()->id;
//  pass the $chekoutId to the front-end to be processed
} catch (\SumUp\Exceptions\SumUpAuthenticationException $e) {
    echo 'Authentication error: ' . $e->getMessage();
} catch (\SumUp\Exceptions\SumUpResponseException $e) {
    echo 'Response error: ' . $e->getMessage();
} catch(\SumUp\Exceptions\SumUpSDKException $e) {
    echo 'SumUp SDK error: ' . $e->getMessage();
}



$headers = array(
     sprintf('Authorization: Bearer %s', $accessToken),
    'Content-Type' => 'application/json'
);
$data = '{
        "payment_type": "card",
        "card": {
          "name": "'.$card_name.'",
          "number": "'.$card_number.'",
          "expiry_month": "'.$expiry_month.'",
          "expiry_year": "'.$expiry_year.'",
          "cvv": "'.$cvv.'"
        }
      }';
$url="https://api.sumup.com/v0.1/checkouts/".$checkoutId;
 $packet_json = json_encode($data);
        $ch = curl_init($url);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");
        curl_setopt($ch, CURLOPT_POSTFIELDS, $packet_json);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        $output = curl_exec($ch);
        $output = json_decode($output, true);

		if (!$output) 
		{
		    return false;
		}

`

**Comment by lyubomir-sumup** [comment]
Please don't provide sensitive data (such as credit details, emails, codes, secrets, etc.)

**Comment by prasadsupare** [comment]
> Please don't provide sensitive data (such as credit details, emails, codes, secrets, etc.)

sir, these are the fake card details used for sandbox testing..

**Comment by prasadsupare** [comment]
This is my index file:

```php


require_once 'sumup/SumUp.php';


try {
			    $sumup = new \SumUp\SumUp ([
			    'app_id'     => 'Xxxxxxxxxxxxxxxxxxxxxx',
			    'app_secret' => 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
			    'grant_type' => 'client_credentials'
			]);
			$accessToken = $sumup->getAccessToken();
			$value = $accessToken->getValue();

    $checkoutService = $sumup->getCheckoutService();
    $checkoutResponse = $checkoutService->create($amount, $currency, $checkoutRef, $payToEmail);
    $checkoutId = $checkoutResponse->getBody()->id;
//  pass the $chekoutId to the front-end to be processed
} catch (\SumUp\Exceptions\SumUpAuthenticationException $e) {
    echo 'Authentication error: ' . $e->getMessage();
} catch (\SumUp\Exceptions\SumUpResponseException $e) {
    echo 'Response error: ' . $e->getMessage();
} catch(\SumUp\Exceptions\SumUpSDKException $e) {
    echo 'SumUp SDK error: ' . $e->getMessage();
}



$headers = array(
     sprintf('Authorization: Bearer %s', $accessToken),
    'Content-Type' => 'application/json'
);
$data = '{
        "payment_type": "card",
        "card": {
          "name": "'.$card_name.'",
          "number": "'.$card_number.'",
          "expiry_month": "'.$expiry_month.'",
          "expiry_year": "'.$expiry_year.'",
          "cvv": "'.$cvv.'"
        }
      }';
$url="https://api.sumup.com/v0.1/checkouts/".$checkoutId;
 $packet_json = json_encode($data);
        $ch = curl_init($url);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");
        curl_setopt($ch, CURLOPT_POSTFIELDS, $packet_json);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        $output = curl_exec($ch);
        $output = json_decode($output, true);

		if (!$output) 
		{
		    return false;
		}


```

**Comment by lyubomir-sumup** [comment]
The recommended way of using the SDK is by [composer](https://getcomposer.org/).
Obviously you don't want to use it so you need to implement [autoloader](https://www.php-fig.org/psr/psr-4/examples/) yourself or to 'require' all files from the SDK one by one.

> NOTE: you must not process (in production) any checkouts with card details from your backend if you are not [PCI DSS](https://www.pcisecuritystandards.org/) certified.

**Comment by prasadsupare** [comment]
Thank you sir! that helped.. But at the last step which is "complete the checkout" i converted  the given curl code to curl php but i'am getting the internal server error response:

**( [message] => Internal Server Error (38bgvurg7jil1) [error_code] => SERVER_ERROR )**

My curl code: 

```php

$headers = array(
    'Authorization' => 'Bearer '.$arr1[0],
    'Content-Type' => 'application/json'
);

$data = '{
        "payment_type": "card",
        "card": {
          "name": "'.$card_name.'",
          "number": "'.$card_number.'",
          "expiry_month": "'.$expiry_month.'",
          "expiry_year": "'.$expiry_year.'",
          "cvv": "'.$cvv.'"
        }
      }';
$url="https://api.sumup.com/v0.1/checkouts/".$checkoutId;

 $packet_json = json_encode($data);
        $ch = curl_init($url);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");
        curl_setopt($ch, CURLOPT_POSTFIELDS, $packet_json);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        $output = curl_exec($ch);
       $output = json_decode($output, true);

print_r($output);


```

and "arr1[0]" is the access token value from getAccessToken()

and access token object response is:


SumUp\Authentication\AccessToken Object ( [value:protected] => xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx [type:protected] => Bearer [expiresIn:protected] => 3600 [scope:protected] => [refreshToken:protected] => ) 



Please can you point out whats wrong?

**Comment by prasadsupare** [comment]
Thank you sir! that helped!! :)

**Comment by lyubomir-sumup** [comment]
Hi, @prasadsupare,
as I said you shouldn't process card details through your backend. The problem in your case is that your `$data` have to be an `array` not a string.

**Comment by baris22** [comment]
How did you fix this issue? I have the same problem. How can I call the classes?
